development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV["REDISCLOUD_URL"]%>
  channel_prefix: RubyProject1_production
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
