development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:908c5d95f5c685d16478a3417f2f1dd3@tarpon.redistogo.com:10135/
  channel_prefix: RubyProject1_production
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
