development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://rediscloud:geImBAeIn5dQkyORwuK90j033AzunVp3@redis-11432.c8.us-east-1-4.ec2.cloud.redislabs.com:11432
  channel_prefix: RubyProject1_production
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
